WinImageBuilder.psm1

The image architecture param was not interpreted as a variable without the parenthesis.

Fixes Cloudbase-Init OS version

---

README.md
UnattendResources/Logon.ps1

-The $programFilesDir variable needs to be "Program Files" always, not "Program Files (x86)" on 64-bit systems, because Cloudbase-Init has a 64-bit version already
-Change the README to address this issue https://github.com/cloudbase/windows-openstack-imaging-tools/issues/26 (added the reference to Unblock-File)

Fixed Program Files variable and added Unblock-File to README

---

WinImageBuilder.psm1

With the old code, the virtio iso is mounted succesfully and the drive
letter is for example, D. But if we execute the powershell cmd
"Test-Path D:\", it returns "False". This issue is soved by calling
"Get-PSDrive" to refresh the active drives.

Refresh PowerShell list of active drives

---

WinImageBuilder.psm1

This pull request has 2 commits:
- Fix for BCDBoot when creating Win7 and Win2008r2 images
- Addition of ExecRetry function for preventing transient errors

Do not use bcdboot /f for Win7 and Win2008r2

---

WinImageBuilder.psm1

This pull request has 2 commits:
- Fix for BCDBoot when creating Win7 and Win2008r2 images
- Addition of ExecRetry function for preventing transient errors

Remove /f flag when creating Win7 and Win2008r2 images

---

UnattendResources/Logon.ps1

Dism clean fails the first time is run on win2016, so we need a retry for its run

Make dism clean redundant on win2016

---

WinImageBuilder.psm1

Cloudbase-Init has two installers - stable and nightly build (Beta). By setting the BetaRelease parameter to false, the stable version will be downloaded and installed, otherwise the beta branch will be used.

 Parameterize Cloudbase-Init installer to use Stable or Beta one

---

Config.psm1
UnattendResources/Logon.ps1

This commit adds the option to generate golden images, which are
cloud images where the long operations are already done (installing
updates and cleaning the extra files).
Note: This image is not ready to be used in a cloud. This image can
be used as a starting point to generate a fully working image.

Added the possibility to generate golden images

---

Config.psm1
WinImageBuilder.psm1

This pull request adds the ability to generate golden image and start to generate an image from a golden one.
- A **golden image** is not ready to be used in a cloud. It can be used as a starting point to generate a fully working one. The major benefits it adds are that it has updates installed and the extra files cleaned. It this way, the major time consuming tasks are already done.
- When we are starting from a golden image, we just install cloudbase-init and do the cleanup process.

Adding golden image support

---

WinImageBuilder.psm1

The image architecture on Windows 7 is "x86" and not 'i386'

Fixed Windows 7 x86 image generation

---

UnattendResources/Logon.ps1

On Windows 10 v1703, there is no AutoLogonCount regkey and the whole
generation fails. We can continue without any issues if that registry
cannot be removed/deleted because it does not exist.

Fixed Windows 10 Creators Update generation

---

Tests/WinImageBuilder.Tests.ps1
WinImageBuilder.psm1

As a VHD cannot be created without specifing a path
with vhd/vhdx extension, the image_path must be, before
the backing VHD is created, converted to have a VHD(X) suffix.

Fixed image path when creating non-hyperv images

---

Config.psm1
UnattendResources/Logon.ps1

Setting this parameter to True allows you to enable
the Administrator account on the client versions
of Windows (which is disabled by default)

Added enable_administrator_account parameter

---

WinImageBuilder.psm1

Typecast $windowsImageConfig.cpu_count to an integer so it can be more reliably compared against the number of logical processors.  Closes #219.

Typecast $windowsImageConfig.cpu_count

---

Config.psm1
WinImageBuilder.psm1

This pull request adds support to slipstream Microsoft KBs and other packages to an offline image via DISM.
It works by introducing a new Config parameter, `extra_packages`, that contains a comma separated list of filepaths to extra packages that will be installed directly into the underlying Windows image at image creation time.
The  `extra_packages` parameter can be used with either `New-WindowsOnlineImage` or `New-WindowsCloudImage` workflows.
```powershell
$kb4457128 = "C:/Path/To/Some/Update/windows10.0-kb4457128-x64_ed9c4b8a5fd2a5d9f55873f8502e4f7495e5a47e.msu"
$kbs = @($kb4457128)
$slipstreamed_kbs =  $kbs -join ","
Set-IniFileValue -Path $configFilePath -Section "Default" -Key "extra_packages" -Value $slipstreamed_kbs
New-WindowsOnlineImage -ConfigFilePath $configFilePath
```
For …

Add offline hook to install custom packages or kbs

---

WinImageBuilder.psm1

The VirtIO drivers would fail to install on Windows 10 editions
because the directory mapping for the driver was missing.
Also added support for the "Client" imageInstallationType.
Addressing issue #226

Added support for Windows 10 VirtIO drivers

---

WinImageBuilder.psm1

While creating UEFI drive Mount-VHD returns an array of partitions'
drive letters, but code assumes that there is just one drive letter.
Returned array is being filtered by partition name 'OS'
and only this one is being optimized.
Resolving issue:
https://github.com/cloudbase/windows-openstack-imaging-tools/issues/248

Resize only OS partition on UEFI drive

---

WinImageBuilder.psm1

Copy-UnattendedResources would fail to install the MaaS hooks because
the InstallMaasHooks parameter was missing during the function
call from inside New-WindowsFromGoldenImage

InstallMaasHooks and VMwareToolsPath added to WindowsFromGoldenImage

---

Config.psm1
WinImageBuilder.psm1

From Windows 1809 and Windows Server 2019 there is a new DISM Features on Demand /Add-Capability toggle. This PR adds the possibility to leverage it. Useful to enable SSH server in the image for example.

Adding /Add-Capability support

---

Tests/WinImageBuilder.Tests.ps1
WinImageBuilder.psm1

Changes:
* Use Optimize-VHD to optimize the allocation of space. The Compact operation is used to optimize the files. This operation reclaims unused blocks as well as rearranges the blocks to be more efficiently packed, which reduces the size of a virtual hard disk file.
To use Optimize-VHD, the virtual hard disk must not be attached or must be attached in read-only mode. 
* hyper-v: remove auto-checkpoint and use static memory
Windows 10 1903 version creates automated checkpoints by
default, which can add a delay in the image generation time.
Static memory is also enabled, as dynamic memory adds a penalty
in the VM performance.

Optimize VHD to reduce image size

---

WinImageBuilder.psm1

Sites like GitHub now require Tls 1.2 or greater to download
data.
https://github.blog/2018-02-01-crypto-removal-notice/

Enforce Tls1.2 in PowerShell

---

Config.psm1
WinImageBuilder.psm1

When installing a directory full of updates, such as from wsusoffline,
there are inevitably some packages which are "not applicable to this
image". When this happens, DISM returns a nonzero exit code and the
image build fails. This configuration allows the user to ignore these
errors and proceed with the image build anyway.

Add config to ignore extra_packages errors

---

Config.psm1
Tests/WinImageBuilder.Tests.ps1
WinImageBuilder.psm1

Added option shrink_image_to_minimum_size which defaults to True,
to create images that have a fixed size, defined by the value of
disk_size.
Optimize-VHD had to be kept as the VHD optimization does not
change the internal size of the disk.

Added option shrink_image_to_minimum_size=True|False

---

Config.psm1
WinImageBuilder.psm1

If enable_custom_wallpaper is set to true, the wallpaper will be
customized. By default, the flag is enabled and the custom
Cloudbase Solutions wallpaper is used.

Added option enable_custom_wallpaper=True|False

---

WinImageBuilder.psm1

The Resize-Partition can fail as the minimum partition size does
not coincide with the minimum resizeable partition size.
Fixes
https://github.com/cloudbase/windows-openstack-imaging-tools/issues/289

Fix Resize-Partition execution

---

WinImageBuilder.psm1

bcdedit and bcdboot executables write their errors in the
error pipe and on some PowerShell shells they throw also
a PowerShell error.
Changing the ErrorActionPreference to 'SilentlyContinue' fixes
the issue.

Fix PS exit code quirk

---

Config.psm1
UnattendResources/Logon.ps1
WinImageBuilder.psm1
kms_product_keys.json

To fully automate the Windows image creation, for non-core
Windows Server images the KMS key needs to be set in the
Unattend.xml so that no manual action is required to
press on 'Skip License' button.
Currently, only Server Standard and Datacenter (core) are enabled.
To enable this option, the value of the config option
product_key needs to be set to default_kms_key.

licensing: added option to use kms keys

---

WinImageBuilder.psm1

When the image is compressed, the imagePath should not be the config image path, as the target/destination of the compression should be different.

Fix image build from golden

---

Config.psm1
Tests/WinImageBuilder.Tests.ps1
Tests/fake-config.ini
UnattendResources/Logon.ps1
WinImageBuilder.psm1

In the offline gold image builder, add config to enable DISM
Cleanup-Image to be run before packaging the image, so that
updates installed during the extra_packages phase can be cleaned
up before packaging.
The following new config options are added:
* updates:clean_updates_offline, default false. If set,
dism cleanup-image will be performed offline, after
any offline updates / components / capabilities were installed.
* updates:clean_updates_online, default true. If set,
dism cleanup-image will be performed while the instance is running,
after the updates were installed.

Allow image cleanup before packaging

---

Config.psm1
UnattendResources/Logon.ps1

New config option time_zone was added in the 'custom' section.
Example:
[custom]
time_zone = "W. Europe Standard Time"
The time zone will be set during online stage, using:
tzutil.exe /s "W. Europe Standard Time"

custom: Added custom timezone configuration

---

Config.psm1
UnattendResources/Logon.ps1

New config option ntp_servers was added in the 'custom' section.
Example:
[custom]
ntp_servers = "0.ch.pool.ntp.org 1.ch.pool.ntp.org"
The ntp servers will be set during online stage, using:
w32tm.exe /config /syncfromflags:manual
/manualpeerlist:"${CustomNtpServers}"
The ntp servers are comma separated.
Fixes:
https://github.com/cloudbase/windows-openstack-imaging-tools/issues/314

Added custom ntp servers option

---

WinImageBuilder.psm1

The image format is required to be in lower caps,
otherwise qemu-img.exe will not recognize it.

Make qemu-img format lower caps

---

WinImageBuilder.psm1

When a compressed image is tested, the backing compressed files are erroneously removed, leading to removing the created image.

Do not remove zip / tar archives

---

UnattendResources/Logon.ps1

First logon animation is always disabled and Administrator account is always enabled on Windows client versions because of bug in conditions that always return true.
```
> function Is-WindowsClient { return $true }
> if (Is-WindowsClient) { Write-Host $true } else { Write-Host $false }
True
> if (Is-WindowsClient -and $true) { Write-Host $true } else { Write-Host $false }
True
> if (Is-WindowsClient -and $false) { Write-Host $true } else { Write-Host $false }
True
```
To compare the return value of a function in a conditional we must put it in parentheses or assign the return value of the function to a variable and use that variable in the conditional. Otherwise we just call Is-WindowsClient with additional parameter $and = $false which is ignored.
Related discussion …

Fix Is-WindowsClient condition

---

UnattendResources/Logon.ps1

If product_key='default_kms_key', the license on Windows 2008 R2
should not be reset, otherwise the dowloads will fail to install
because Windows will not find a valid license.
Added better logs for Windows and PowerShell version.

Do not reset license on Windows 2008R2

---

Config.psm1
UnattendResources/Logon.ps1

Added option to set cloudbase-init service to auto-delayed start.
```ini
[cloudbase_init]
cloudbase_init_delayed_start=False
```
Sometimes we need cloudbase-init service to be set to auto delayed
start, to make sure that all the Windows services are up and running
when cloudbase-init runs. This scenario might fix the problems with
NETLBFO bond, when cloudbase-init tries to create the bonds, but the
bonding networking services are not ready and silent failures can occur.
Fixes:
https://github.com/cloudbase/windows-openstack-imaging-tools/issues/341

Add option to set cloudbase-init service to auto-delayed start

---

WinImageBuilder.psm1

If multiple images are generated using the same VirtIO ISO,
there is a chance that the imaging tool will dismount the VirtIO
ISO at a path in use, which triggers an error to apply the
drivers.
Copying the ISO to a backup file and mounting that ISO will
fix the issue.
This fix might be time / space consuming, but it is the only way
to make sure that the proper ISO is unmounted,
as there is no way to get the mount
point from the ISO file path itself, without making a persistance layer
logic to track which ISO file corresponds to which mount point and make
another persistence layer to track the mount points. Even if the mount
points and file paths are tracked, in highly used envs, there is a
probability that the mount points cannot be properly tracked due to
concurrency issues (when 2 ISOs …

Fixed multiple iso mount points for VirtIO

---

README.md

Windows Server 2019 was supported from its initial release,
as it was an incremental upgrade for the Windows Server 2016 version.

Officialize support Windows Server 2019

---

Config.psm1
Examples/windows-image-config-example.ini
Tests/WinImageBuilder.Tests.ps1
UnattendResources/Logon.ps1
WinImageBuilder.psm1

Added option to install Qemu Guest Agents:
[custom]
install_qemu_ga=False
If set to True, it will download and install the Qemu Guest
Agents from Fedora website. The base path for the agents is
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-qemu-ga/qemu-ga-win-100.0.0.0-3.el7ev/
The downloaded MSI will be chosen depending on the architecture of the
image, x86 or x64.
For example, on x64 images, the following MSI installer will be
downloaded and used:
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-qemu-ga/qemu-ga-win-100.0.0.0-3.el7ev/qemu-ga-x64.msi
By default, the imaging tools will not install the Qemu Guest
Agents.
The MSI will install two services on the Windows image:
* QEMU-GA
* QEMU Guest Agent VSS Provider
The Qemu Guest Agents …

Added option to install Qemu Guest Agents

---

UnattendResources/Logon.ps1

ICMPv6 uses different message types than ICMPv4. So in order to enable ICMPv6 echo requests we have to used message type 128 instead of 8.  See https://de.wikipedia.org/wiki/ICMPv6 for reference.

fix: use correct icmpv6 type for echo request

---

Config.psm1
UnattendResources/Logon.ps1

For Windows 2012 R2 installing the .net3.5 feature is impossible after you install the Windows updates.
Reference [here](https://support.microsoft.com/en-us/topic/update-for-the-net-framework-3-5-on-windows-8-windows-8-1-windows-server-2012-and-windows-server-2012-r2-c5c4baac-1708-d32d-2cfb-dd94e4a91b2a)
This PR introduces a parameter that if set to True  .net3.5 will be installed before any updates are installed

Added install_net_3_5 feature for Win 2012R2

---

WinImageBuilder.psm1

Add support for 2k22 virtio drivers.
Build versions are from https://www.techthoughts.info/windows-version-numbers/

virtio: use 2k22 virtio drivers

---

Examples/config/kubevirt/cloudbase-init-unattend.conf
Examples/config/kubevirt/cloudbase-init.conf

Use the correct NoCloudConfigDriveService class path and limited the unattended list of plugins to the 3 that are being set by the installer.

kubevirt: fix nocloud class name and limited unattend plugins

---

WinImageBuilder.psm1

Currently, when building Windows Server 2025 images, we are using the VirtIO driver binaries for Windows Server 2022. This PR introduces a dedicated mapping for 2k25, using the appropriate build numbers.
The build versions are from https://learn.microsoft.com/en-us/windows-server/get-started/windows-server-release-info

Add support for 2k25 virtio drivers
