cloudbase/windows-imaging-tools

- WinImageBuilder.psm1
Fix GenerateConfigFile to properly set preferences.
> Fix GenerateConfig

- UnattendResources/curtin/finalize
This PR fixes finalize to work with latest version of curtin.
> Add maas1.9 support

- WinImageBuilder.psm1
This commit adds the parameter $VirtIOBasePath to the New-WindowsCloudImage method, where you can specify a folder with the VirtIO folder structure(for example where you mounted the Fedora VirtIO ISO).
Fixes for mapping of the VirtIO drivers with the appropriate Windows versions are added.
A fix for mounting the VirtIO ISO has been added, as PS did not automatically refreshed the list of mount points after mount .
> Added support for virtio folder and fixed virtio iso mount

- UnattendResources/Logon.ps1
- UnattendTemplate.xml
- WinImageBuilder.psm1
- Clean image of unused update files
- Shrink the volume
> Clean-up unnecessary data after updates

- UnattendResources/Logon.ps1
> Release IP for a faster boot process

- README.md
Windows Server 2016 has been verified to work with existing instructions, including successful Pester tests.
> Adds Windows Server 2016 verified compability

- UnattendResources/Logon.ps1
Fixed various coding style issues regarding brackets and spacing.
> Fixed powershell coding style in Logon.ps1

- WinImageBuilder.psm1
This commit adds the possibility to create a password protected zip from
the generated image.
This option is enabled by setting a value for the "ZipPassword" parameter.
> Added the possibility to create a password protected zip

- Config.psm1
- README.md
- Tests/WinImageBuilder.Tests.ps1
- Tests/fake-config.ini
- WinImageBuilder.psm1
This commit switches the generation workflow from a script to a config
file method.
> Generate cloud images from config file

- WinImageBuilder.psm1
We need to make sure New-WindowsCloudImage returns a .vhdx image when
it's called as a standalone function, as opposed to being called by
New-WindowsOnlineImage.
Also, this fix ensures New-ProtectedZip is called only once when
is required by New-WindowsOnlineImage.
> Adding a second ConfigFile for the image generation

- WinImageBuilder.psm1
This pull request adds the missing `$` variable sign to the `Test-Path` check.
> Added missing variable sign

- Examples/create-windows-cloud-image.ps1
- Examples/create-windows-online-cloud-image.ps1
This commit contains updated examples according to the new code
> Updated Examples

- README.md
I don't like abbreviations/names used without context (MAAS in this case) and I like know what's going on - so I'm adding links to projects webpages.
> Names: OpenStack and MAAS expanded to links

- Config.psm1
- UnattendResources/FirstLogon.ps1
- UnattendResources/Logon.ps1
- UnattendResources/Specialize.ps1
- UnattendResources/ini.psm1
- WinImageBuilder.psm1
> Fixed coding style errors found by PSAnalyzer

- UnattendResources/Logon.ps1
This commit adds the possibility to activate the license on
golden images if the product_key and gold_image parameters
are set to $true in Config.psm1
> Adding the license activation for golden images

- Config.psm1
- Examples/create-windows-online-cloud-image.ps1
- WinImageBuilder.psm1
Added compress option for QCOW2 images to Convert-VirtualDisk method and compress_qcow2 parameter to Config.psm1
> Added compress_qcow2 parameter to Config.psm1

- Config.psm1
- WinImageBuilder.psm1
This parameter allows you to chose the end compression format of the image.
Example : compression_format = "tar.gz"
> Added compression_format parameter

- ImageChecks.ps1
> Added MAAS/Hyper-V/KVM checks

- Examples/create-windows-cloud-image.ps1
- Examples/create-windows-online-cloud-image.ps1
Update VirtIO ISO link to 0.1.141 version
> Update VirtIO ISO link to 0.1.141 version

- Examples/create-digital-ocean-windows-image.ps1
- Examples/create-windows-cloud-image.ps1
- Examples/create-windows-online-cloud-image.ps1
When called from outside the repository, the invocation of git in the example scripts fails.
This PR provides a fix for that.
> Fix git invocation when called from elsewhere

- WinImageBuilder.psm1
> Fix parameter name when using Add-VirtIODriversFromISO

- Config.psm1
- UnattendResources/Logon.ps1
Fixes issue https://github.com/cloudbase/windows-openstack-imaging-tools/issues/192
> Fix IPv6 addressing on OpenStack/CloudStack

- Tests/WinImageBuilder.Tests.ps1
- WinImageBuilder.psm1
Use binary search to find the best partition size
> Binary resize partition

- UnattendResources/Logon.ps1
- WinImageBuilder.psm1
Added Hyper-V KVP based logging for online step
Added KVP based logging for better information on what
happens during the online image generation stage.
> Added Hyper-V KVP based logging for online step

- Config.psm1
- UnattendResources/Logon.ps1
The config option added will allow the disabling of the first login
animation dispalyed on client versions of Windows.
> Add config option to disable first logon animation

- WinImageBuilder.psm1
On UEFI disks, there are multiple partitions. We only care about
the Basic one, where the OS filesystem resides.
> Fix drive letter get when using UEFI partitions

- UnattendResources/Logon.ps1
- WinImageBuilder.psm1
decompress: keep original file for ungzip
Fix drivers apply on a golden image
Fix KMS licensing reset
> Fixes drivers apply, decompress-file and KMS licensing reset

- Config.psm1
- UnattendResources/Logon.ps1
- WinImageBuilder.psm1
Added reboot in case dism fails to clean updates …
Do not remove backing zip/tar on decompress
Add enable_active_mode option
Report errors from the online stage
Added option to disable_secure_boot for generation 2 VMs
> Various fixes

- WinImageBuilder.psm1
In some cases, the resources used to generate images can
be located at different locations and need to be managed
separately due to size issues.
Adding support for multiple custom resources or scripts,
comma separated, will make life easier to maintain image
generation.
> Added support for multiple custom resources / scripts

- UnattendResources/Logon.ps1
Added logging for custom scripts exit codes and refactored
the logon steps which did not have proper methods.
A custom hook script can have special exit codes:
* 0 - The Logon script will continue running
* 1004 - The Logon script will exit after hook execution
* 1005 - The Logon script will perform a reboot
* 1006 - The Logong script will perform a shutdown
* Other exit code, the Logon script will throw an error and stop
> Added better logging for logon steps

- WinImageBuilder.psm1
If multiple images are created at the same time from a gold VHD,
there is a chance that some of them do not boot because HyperV
boot environment does not recognize the boot device anymore
with error code 0xc00000e.
Resetting the BCD store to locate the os device and resetting the
VHD GUID should solve the issue.
> Reset BCD store for images created from gold

- README.md
Reverts cloudbase/windows-openstack-imaging-tools#317
> Revert "Updated code checker badge"

- Examples/windows-image-config-example.ini
Added a Windows image config example with the latest custom configuration found in Config.psm1
This file was generated automatically:
```powershell
Import-Module Config.psm1
New-WindowsImageConfig windows-image-config-example.ini
```
> Added image config example

- UnattendResources/Logon.ps1
The following configurations were defaulted to wrong values,
as they were boolean, but were treated as string.
```ini
[default]
enable_shutdown_without_logon=False
enable_ping_requests=False
enable_ipv6_eui64=False
[cloudbase_init]
cloudbase_init_use_local_system=False
```
If none of these config values were set in the config file,
there was no regression.
If any config value was set, they were considered True even if
the config value was False (False as a string is True).
Fixes
https://github.com/cloudbase/windows-openstack-imaging-tools/issues/330
> Fixed boolean configurations in Logon.ps1

- Examples/config/azure/Readme.md
- Examples/config/azure/cloudbase-init-unattend.conf
- Examples/config/azure/cloudbase-init.conf
Added examples configs for image builder and cloudbase-init so that the
image created works on Azure.
> examples: added example config and how-to for Azure

- WinImageBuilder.psm1
Use Windows build numbers to map the Fedora VirtIO drivers to be
installed.
Build number intervals for each Windows version in CSV format:
Windows Version, Minimum Build, Maximum Build, IsServerVersion
"2k8", 6000, 6003, true
"2k8r2", 7600, 8400, true
"w7", 7600, 8400, false
"2k12", 9200, 9200, true
"w8", 9200, 9200, false
"2k12r2", 9600, 9900, true
"w8.1", 9600, 9900, false
"2k16", 14393, 16299, true
"w10", 10240, infinity, false
"2k19", 17763, inifinity, true
> virtio: use 2k19 virtio drivers

- WinImageBuilder.psm1
> fix: split extra_features into array

- WinImageBuilder.psm1
> Retry with local bcdboot.exe not only for old versions of bcdboot.exe
